### ISSUE TITLE
问下，假如服务端redis没有设置密码验证该怎么做

### ISSUE THREAD

**Issue by langyan1022** [drtrang/redisson-spring-boot#10]
我现在使用的是 哨兵模式  ，由于一些原因redis 服务端是暂时没办法设置密码（不是自己的redis服务）
redisson.sentinel.password=
或者直接把这个注释掉

启动链接redis 会报这个错误：
org.redisson.client.RedisException: ERR Client sent AUTH, but no password is set. channel: [id: 0x7616e564, L:/10.193.48.101:52715 - R:10.193.46.203/10.193.46.203:6380] command: (AUTH), params: []

请问下改怎么解决

**Comment by drtrang** [comment]
@langyan1022 

这个异常是说 redis 服务端没有密码，但是客户端请求的时候发送了 AUTH 命令。
你可以删掉 password 的配置，如果还不行，请贴一下配置。

**Comment by langyan1022** [comment]
嗯，刚开始删掉了不行，后来重新打了个包可以了，应该是缓存的事儿，谢谢
