### ISSUE TITLE
可以完善下使用文档吗？

### ISSUE THREAD

**Issue by thinwonton** [drtrang/redisson-spring-boot#4]
你好，请问可以抽点时间完善下使用文档吗？

**Comment by thinwonton** [comment]
现在集成到spring boot里，总是无法注入。

Unsatisfied dependency expressed through field 'redissonClient'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.redisson.api.RedissonClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

debug了一下，好像都进不去 RedissonAutoConfiguration类RedissonClient redisson()

**Comment by drtrang** [comment]
redisson 在其 wiki 里很详细的使用文档：https://github.com/redisson/redisson/wiki/%E7%9B%AE%E5%BD%95

starter 只是通过配置文件的方式去配置 redisson，配置项和 redisson 本身的配置相同，详细配置可以查看 [RedissonProperties](https://github.com/drtrang/redisson-spring-boot/blob/master/redisson-spring-boot-autoconfigure/src/main/java/com/github/trang/redisson/autoconfigure/RedissonProperties.java) 和 [RedissonSpringProperties](https://github.com/drtrang/redisson-spring-boot/blob/master/redisson-spring-boot-autoconfigure/src/main/java/com/github/trang/redisson/autoconfigure/RedissonSpringProperties.java) 这两个类，每个属性上都有注释。

其次，在写 yaml 或者 properties 配置文件的时候也会有自动提示供参考：
![image](https://user-images.githubusercontent.com/13851701/40461585-94db254c-5f3e-11e8-8e9b-db71564f825b.png)

**Comment by drtrang** [comment]
@ThinWonton 

1.2.2 版本更新已提交，敬请更新（同步到代理仓库 1 小时左右），修复了上述问题。
如仍有问题，可随时联系我。
