### ISSUE TITLE
1.2.1版本的问题

### ISSUE THREAD

**Issue by langyan1022** [drtrang/redisson-spring-boot#5]
@ConfigurationProperties(prefix = "redisson")
@Getter
@Setter
public class RedissonProperties {}

@ConfigurationProperties(prefix = "redisson") 在1.1.1 中应该是@ConfigurationProperties(prefix = "spring.redisson") 

但是在RedissonAutoConfiguration 中有@ConditionalOnProperty(prefix = "spring.redisson", name = "type")

这样就得这样
spring.redisson.type=sentinel
redisson.type=sentinel 
配置才行了，看着比较蹩脚

能恢复1.1.1版本的方式么

**Comment by drtrang** [comment]
这是 1.2.1 中存在的 bug，预计明天修复

**Comment by langyan1022** [comment]
好的，谢谢了

**Comment by drtrang** [comment]
@langyan1022 

1.2.2 版本更新已提交，敬请更新（同步到代理仓库 1 小时左右），调整了配置的参数。
如仍有问题，可随时联系我。
目前 redisson 配置的前缀是 `redisson`，redisson spring 配置的前缀是 `spring.redisson`。
