### ISSUE TITLE
阿里云redis 禁用eval

### ISSUE THREAD

**Issue by 201314** [drtrang/redisson-spring-boot#7]
![_20180704112454](https://user-images.githubusercontent.com/3360865/42255174-1041a36a-7f7d-11e8-93a9-1bdc16adc5ac.png)
阿里云禁用了redis的eval，有没有其他方式，在不启用eval，达到分布式锁的效果。

**Comment by drtrang** [comment]
redisson 中大量使用了 `eval` 命令来执行 lua 脚本，不只是 Redisson#getLock()，如果云服务不支持的话，建议改用其他的 redis client 吧。

**Comment by gyb** [comment]
阿里云现在只要升级redis的小版本号就支持eval了，一键搞定
![redis](https://user-images.githubusercontent.com/1411909/43881246-28b82996-9bde-11e8-87a8-b261f33ec5c9.png)

**Comment by drtrang** [comment]
这样最好了
