### ISSUE TITLE
给一份属性文件配置清单吧

### ISSUE THREAD

**Issue by zhuchaowei** [drtrang/redisson-spring-boot#8]
给一份属性文件配置清单吧

**Comment by drtrang** [comment]
抽空整理一下，暂时可以先看这个文件，里面包含了 redisson-spring-boot-starter 所有的自动配置项。

![image](https://user-images.githubusercontent.com/13851701/44134530-f54e64e4-a097-11e8-80fe-702ba683200e.png)

**Comment by zhuchaowei** [comment]
At least two sentinels should be defined in Redis configuration!  这个错误 怎么回事儿  我是哨兵模式的 
至少2个配置 是啥意思？？

**Comment by drtrang** [comment]
贴一下你的配置吧

**Comment by zhuchaowei** [comment]
找到问题了 哨兵进程没起来
